### ISSUE TITLE
npm ERR! puppeteer@3.3.0 install: `node install.js`

### ISSUE THREAD

**Issue by nocomp** [FlameOfIgnis/puff#1]
hi,
thxx for your tool, wanted to give it a try, but got this error during the install on ubuntu 18.04
i ve attached the log file in case it can help

npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN puff-fuzz@0.0.2 No repository field.
npm ERR! Linux 4.15.0-108-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@3.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.3.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nocomp/tools/puff/npm-debug.log
[npm-debug.log](https://github.com/FlameOfIgnis/puff/files/4845828/npm-debug.log)

**Comment by ignis-sec** [comment]
Hello! This seems to be an upstream issue related to either puppeteer (the dependency im using for chromium) or with npm itself.


Could you try a few things?


Are you trying to run from the source and getting this error during `npm install`? If so, [this issue](https://github.com/npm/npm/issues/7308) suggests running `npm install --no-bin-links` instead.


If not, could you try installing and running through npm package? `npm install -g puff-fuzz`

Let me know if those don't work. I'll be looking into the issue regardless of it being an issue on the upstream if thats the case

**Comment by nocomp** [comment]
hi @FlameOfIgnis thxx for your response,
here is te first output for -no-bin-links, same issue

nocomp@P0wnB0x:~/tools/puff$ npm install --no-bin-links
loadDep:puppeteer → netwo ▄ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ws → request      ▀ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> puppeteer@3.3.0 install /home/nocomp/tools/puff/node_modules/puppeteer
> node install.js

/home/nocomp/tools/puff/node_modules/puppeteer/install.js:175
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN puff-fuzz@0.0.2 No repository field.
npm ERR! Linux 4.15.0-108-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@3.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.3.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nocomp/tools/puff/npm-debug.log
nocomp@P0wnB0x:~/tools/puff$

**Comment by nocomp** [comment]
here is the output for -g puff-fuzz, yes i am installing from source.
thxx for your time

nocomp@P0wnB0x:~/tools/puff$ npm install -g puff-fuzz
loadDep:puppeteer → resol ▌ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ws → request      ▐ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ puff-fuzz@0.0.2 
  ├── commander@5.1.0 
  └─┬ puppeteer@3.3.0 
    ├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
    ├─┬ debug@4.1.1 
    │ └── ms@2.1.2 
    ├─┬ extract-zip@2.0.1 
    │ ├─┬ @types/yauzl@2.9.1 
    │ │ └── @types/node@14.0.14 
    │ ├── get-stream@5.1.0 
    │ └─┬ yauzl@2.10.0 
    │   ├── buffer-crc32@0.2.13 
    │   └─┬ fd-slicer@1.1.0 
    │     └── pend@1.2.0 
    ├─┬ https-proxy-agent@4.0.0 
    │ └── agent-base@5.1.1 
    ├── mime@2.4.6 
    ├── progress@2.0.3 
    ├── proxy-from-env@1.1.0 
    ├─┬ rimraf@3.0.2 
    │ └─┬ glob@7.1.6 
    │   ├── fs.realpath@1.0.0 
    │   ├─┬ inflight@1.0.6 
    │   │ └── wrappy@1.0.2 
    │   ├── inherits@2.0.4 
    │   ├─┬ minimatch@3.0.4 
    │   │ └─┬ brace-expansion@1.1.11 
    │   │   ├── balanced-match@1.0.0 
    │   │   └── concat-map@0.0.1 
    │   ├── once@1.4.0 
    │   └── path-is-absolute@1.0.1 
    ├─┬ tar-fs@2.1.0 
    │ ├── chownr@1.1.4 
    │ ├── mkdirp-classic@0.5.3 
    │ ├─┬ pump@3.0.0 
    │ │ └── end-of-stream@1.4.4 
    │ └─┬ tar-stream@2.1.2 
    │   ├── bl@4.0.2 
    │   ├── fs-constants@1.0.0 
    │   └─┬ readable-stream@3.6.0 
    │     ├─┬ string_decoder@1.3.0 
    │     │ └── safe-buffer@5.2.1 
    │     └── util-deprecate@1.0.2 
    ├─┬ unbzip2-stream@1.4.3 
    │ ├─┬ buffer@5.6.0 
    │ │ ├── base64-js@1.3.1 
    │ │ └── ieee754@1.1.13 
    │ └── through@2.3.8 
    ├── UNMET PEER DEPENDENCY utf-8-validate@^5.0.2
    └── ws@7.3.0 

npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 4.15.0-108-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "puff-fuzz"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nocomp/tools/puff/npm-debug.log
nocomp@P0wnB0x:~/tools/puff$

**Comment by ignis-sec** [comment]
I'll research on the issue with npm install on your case shortly, but meanwhile, with `npm install -g puff-fuzz` it looks like you are having a simple permission misconfiguration (`cant write under /usr/local/lib/node_modules as current user`).

A simple sudo should do the trick.

`sudo npm install -g puff-fuzz`

**Comment by nocomp** [comment]
Thxx a lot i ll try tomorrow, already back home

**Comment by nocomp** [comment]
damm no luck!!!
i ve attached logfile

thxx for your time


nocomp@P0wnB0x:~/tools/puff$ sudo npm install -g puff-fuzz
[sudo] Mot de passe de nocomp : 
loadDep:puppeteer → resol ▐ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ws → request      ▄ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/puff -> /usr/local/lib/node_modules/puff-fuzz/puff.js

> puppeteer@3.3.0 install /usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer
> node install.js

/usr/local/lib/node_modules/puff-fuzz/node_modules/puppeteer/install.js:175
            } catch {
                    ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
/usr/local/lib
└── (empty)

npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 4.15.0-108-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "puff-fuzz"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@3.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.3.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nocomp/tools/puff/npm-debug.log
npm ERR! code 1



[npm-debug.log](https://github.com/FlameOfIgnis/puff/files/4849950/npm-debug.log)

**Comment by ignis-sec** [comment]
Hello! I just noticed the versions of npm and node you are using are quite out of date.

node v8.10.0 was released 2 and a half years ago and was cut from support 1 and a half years ago.
npm v3.5.2 is around the same age. 

Could you update those and retry? Maybe that might be causing the problem with puppeteer install scripts

**Comment by nocomp** [comment]
ola
ok i ll do that this noon
thxxxx

**Comment by nocomp** [comment]
hmmm
weird

nocomp@P0wnB0x:~/tools/puff$ sudo apt install nodejs
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
nodejs est déjà la version la plus récente (8.10.0~dfsg-2ubuntu0.4).
nodejs passé en « installé manuellement ».
0 mis à jour, 0 nouvellement installés, 0 à enlever et 9 non mis à jour.
nocomp@P0wnB0x:~/tools/puff$ sudo apt install npm
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
npm est déjà la version la plus récente (3.5.2-0ubuntu4).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 9 non mis à jour.
nocomp@P0wnB0x:~/tools/puff$

**Comment by ignis-sec** [comment]
Sorry for the delayed reply, i really suggest using node version manager(nvm) for linux, its really helpful :)
