### ISSUE TITLE
Hey can you help me out 

### ISSUE THREAD

**Issue by MR-pentestGuy** [FlameOfIgnis/puff#8]
i am using wsl and i have installed npm but i get these errors 
i have tried looking them in google but was unable to find the main cause 

command i ran cat urls.txt (has FUZZ) | puff -w xss.txt 

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/puff-fuzz/config.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at resolveChromiumPath (/usr/local/lib/node_modules/puff-fuzz/configwiz.js:33:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/puff-fuzz/puff.js:61:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by 0x5ECF4ULT** [comment]
Your error is in the first line. It explicitly says "permission denied". Check the access bits.
